name: Print Message
on:
  workflow_dispatch: {}
    # inputs:
    #   serviceId:
    #     required: true
    #     description: 'Deploy parameters'
    #   semanticVersion:
    #     required: true
    #   repositoryName:
    #     required: true
    #   awsRegion:
    #     required: true
    #   cdkOutZipSha:
    #     required: true

# env:
#   DEPLOY_PARAMETERS: ${{ inputs.deployParameters }}

# jobs:
#   create-output:
#     runs-on: ubuntu-latest
#     outputs: 
#       CdkOutZipSha: ${{ steps.create-output.outputs.CDK_OUT_ZIP_SHA256 }}
#     steps:
#       - name: Create output
#         id: create-output
#         run: |
#           echo "CDK_OUT_ZIP_SHA256=value" >> $GITHUB_OUTPUT
#   echo-output:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Echo output
#         run: echo ${{ needs.create-output.outputs.CdkOutZipSha }}

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
