name: Print Message
on:
  workflow_dispatch: {}
    # inputs:
    #   serviceId:
    #     required: true
    #     description: 'Deploy parameters'
    #   semanticVersion:
    #     required: true
    #   repositoryName:
    #     required: true
    #   awsRegion:
    #     required: true
    #   cdkOutZipSha:
    #     required: true

# env:
#   DEPLOY_PARAMETERS: ${{ inputs.deployParameters }}

# jobs:
#   create-output:
#     runs-on: ubuntu-latest
#     outputs: 
#       CdkOutZipSha: ${{ steps.create-output.outputs.CDK_OUT_ZIP_SHA256 }}
#     steps:
#       - name: Create output
#         id: create-output
#         run: |
#           echo "CDK_OUT_ZIP_SHA256=value" >> $GITHUB_OUTPUT
#   echo-output:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Echo output
#         run: echo ${{ needs.create-output.outputs.CdkOutZipSha }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Check if yq and jq are installed
        id: get-cdk-out-zip-sha
        run: |
          jq --help
          yq --help

