name: Print Message
on:
  workflow_dispatch:
    inputs:
      serviceId:
        required: true
        description: 'Deploy parameters'
      semanticVersion:
        required: true
      repositoryName:
        required: true
      awsRegion:
        required: true
      cdkOutZipSha:
        required: true

env:
  DEPLOY_PARAMETERS: ${{ inputs.deployParameters }}

jobs:
  create-output:
    runs-on: ubuntu-latest
    output: ${{ steps.create-output.CDK_OUT_ZIP_SHA256.test }}
    steps:
      - name: Create output
        id: create-output
        run: |
          echo "CDK_OUT_ZIP_SHA256=value" >> $GITHUB_OUTPUT
  echo-output:
    runs-on: ubuntu-latest
    steps:
      run: echo ${{ steps.create-output.CDK_OUT_ZIP_SHA256.test }}
